targets = [ "//:type_index" ]

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
version = "1.69.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
version = "1.69.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
version = "1.69.0"
