manifest = "6764088d4ccb2b1addd48abfc8c9ba252366d72a7f5d158aa6eba3b44f5637d8"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw_exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.59.0" ]
revision = "b8a861102681be539be9c889cd643986f171c364"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.59.0" ]
revision = "ec90e8c6b2f388644b586d11eb1a3543028fa1f5"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.59.0" ]
revision = "b12fabbbe87ec5ebc96b6a0d3a8f1b771d95224f"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.59.0" ]
revision = "e19e7ba52894c7e2b48d6e344a245e1d58fac51e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.59.0" ]
revision = "6019dca782a1a7b7e7e105d67216d8f824423101"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.59.0" ]
revision = "73bbb0b61b9d05696252886e840e7f79c14e27ce"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.59.0" ]
revision = "768330940957238cccb17d6e3449f08569656daf"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.59.0" ]
revision = "06f80557aba297b003135535cdc69de522326c50"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.59.0" ]
revision = "3f5e6e8ab2cc0f5474d6e445dae2d4f959dc0803"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.59.0" ]
revision = "103e6b45eec26ac91156cfeb45450fa8ec375369"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.59.0" ]
revision = "c018d77dfb00804208e6535cc8d99a1daf264ac6"
