manifest = "be472bda5be71f5987cac3615f5d42d42ea48da5b79daab0214743940a6d89b8"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw_exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.65.1" ]
revision = "f52c6500fd6e7409de7724611f7e6ece82702aa4"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.65.1" ]
revision = "ef899f910b922b982581c55683d22a30ed10e2ab"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.65.1" ]
revision = "1860b33ae4c45109e54f6cd810b63a767bd6f381"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.65.1" ]
revision = "2800c1da8c0a7690f1b2984df9de9863096ee22e"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.65.1" ]
revision = "dfd1a8c32d76184a8ffe83d63c3a216303dc9085"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.65.1" ]
revision = "ca49cf363c3166b7a53afc58c2fc82824f415855"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.65.1" ]
revision = "53c1a2e2b254dd5a3512c71b223e5a48bedcc3a7"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.65.1" ]
revision = "34a98fcec1a24138c32e2a13281f8d26936e4e28"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.65.1" ]
revision = "35824adf3a532420f3b579bca4ed5e71f60c920d"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.65.1" ]
revision = "6e6c057b13b5f61e6157330ec30fe6cc3e8503b8"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.65.1" ]
revision = "da125e1167ab1ce61ee6382d815d6687ceeae311"
