manifest = "a91ae3575a42b014053d0d3f844e131086b17f405d8c664ee9fb123e7b5c9859"

[[dependency]]
package = "github.com/buckaroo-pm/boost-container_hash"
target = "//:container_hash"

[[dependency]]
package = "github.com/buckaroo-pm/boost-static_assert"
target = "//:static_assert"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw_exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.57.0" ]
revision = "e4476f3159e98aebaa3a057bd2670653cb778d48"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.57.0" ]
revision = "ee7d5652f970bde066501c7cee1d0d2ad43c2348"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.57.0" ]
revision = "bcdddbb94c34c498170c0682716452220446733f"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.57.0" ]
revision = "9194d8422e508b914041aad8c97a55b712cf4855"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.57.0" ]
revision = "08aef274380d048f40aea0f40be03d3c943c0917"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.57.0" ]
revision = "2d919cee0368f6dcef90b5010755588defadeb5e"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.57.0" ]
revision = "701273f2c2f1da1f06a00b11ee15f30a358a775c"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.57.0" ]
revision = "1c6733c3798004871da07f1ca08b533b1293b597"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.57.0" ]
revision = "7e886911750f84477833ba575aa654092c553cd4"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.57.0" ]
revision = "b71c8285ba07563884f165ae769db3cd5a5dc45a"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.57.0" ]
revision = "672b552c874c72529564a79448c4b48b966ba7c5"
